#!/bin/sh
# run_tests.sh - Test runner for make.sh
# Usage: ./run_tests.sh [filter]
#   filter: optional string to match test directory names (e.g. "01" runs only test 01)

set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
MAKE_SH_BIN="${SCRIPT_DIR}/../target/release/make.sh"
TESTS_DIR="$SCRIPT_DIR"
FILTER="${1:-}"

# Color support
if command -v tput >/dev/null 2>&1 && tput colors >/dev/null 2>&1 && [ "$(tput colors)" -ge 8 ]; then
  GREEN=$(tput setaf 2)
  RED=$(tput setaf 1)
  YELLOW=$(tput setaf 3)
  BOLD=$(tput bold)
  RESET=$(tput sgr0)
else
  GREEN=""
  RED=""
  YELLOW=""
  BOLD=""
  RESET=""
fi

# Counters
PASS_COUNT=0
FAIL_COUNT=0
SKIP_COUNT=0

# Check dependencies
if ! command -v make >/dev/null 2>&1; then
  printf '%s%sWARNING:%s GNU make not found - cannot generate expected output\n' "$BOLD" "$YELLOW" "$RESET"
fi

if [ ! -f "$MAKE_SH_BIN" ]; then
  printf '%s%sERROR:%s make.sh binary not found at: %s\n' "$BOLD" "$RED" "$RESET" "$MAKE_SH_BIN"
  printf 'Run: mush build --release\n'
  exit 1
fi

# Test case arguments: test name, dir, args
run_test() {
  local test_name; test_name="$1"
  local test_dir; test_dir="$2"
  local make_args; make_args="$3"  # extra args to pass (space-separated)

  # Apply filter
  if [ -n "$FILTER" ]; then
    case "$test_name" in
      *"$FILTER"*)
        ;;
      *)
        SKIP_COUNT=$((SKIP_COUNT + 1))
        return 0
        ;;
    esac
  fi

  # Create a clean temp working copy
  local tmpdir; tmpdir=$(mktemp -d)
  # Copy test directory contents to tmpdir
  cp -r "${test_dir}/." "$tmpdir/"

  local expected_file; expected_file="${tmpdir}/expected.txt"
  local actual_file; actual_file="${tmpdir}/actual.txt"
  local diff_file; diff_file="${tmpdir}/diff.txt"

  # Run GNU make to get expected output (clean run)
  local gnu_make_exit; gnu_make_exit=0
  if command -v make >/dev/null 2>&1; then
    # shellcheck disable=SC2086
    (cd "$tmpdir" && make -f Makefile $make_args 2>&1) > "$expected_file" || gnu_make_exit=$?
  else
    printf '(no gnu make)\n' > "$expected_file"
  fi

  # Clean up any files generated by GNU make for a fresh make.sh run
  # Remove non-Makefile files that were created
  (
    cd "$tmpdir"
    # Keep Makefile, remove build artifacts
    find . -maxdepth 1 -type f ! -name 'Makefile' ! -name 'expected.txt' -delete 2>/dev/null || true
  )

  # Run make.sh to get actual output
  local make_sh_exit; make_sh_exit=0
  # shellcheck disable=SC2086
  (cd "$tmpdir" && "$MAKE_SH_BIN" -f Makefile $make_args 2>&1) > "$actual_file" || make_sh_exit=$?

  # Compare outputs
  local test_passed; test_passed=1

  if diff -u "$expected_file" "$actual_file" > "$diff_file" 2>&1; then
    test_passed=1
  else
    test_passed=0
  fi

  # Report result
  if [ "$test_passed" = "1" ]; then
    printf '%s%sPASS%s %s\n' "$BOLD" "$GREEN" "$RESET" "$test_name"
    PASS_COUNT=$((PASS_COUNT + 1))
  else
    printf '%s%sFAIL%s %s\n' "$BOLD" "$RED" "$RESET" "$test_name"
    printf '  Expected exit: %s  Actual exit: %s\n' "$gnu_make_exit" "$make_sh_exit"
    printf '  Diff (expected vs actual):\n'
    # Indent the diff output
    while IFS= read -r diff_line; do
      printf '    %s\n' "$diff_line"
    done < "$diff_file"
    FAIL_COUNT=$((FAIL_COUNT + 1))
  fi

  # Cleanup
  rm -rf "$tmpdir"
}

# Discover and run tests
printf '\n%s%smake.sh Test Suite%s\n' "$BOLD" "$YELLOW" "$RESET"
printf '%s\n' "$(printf '%0.s-' $(seq 1 40))"
printf 'Binary: %s\n' "$MAKE_SH_BIN"
printf '\n'

# Run each test directory
for test_dir in "$TESTS_DIR"/[0-9][0-9]_*/; do
  if [ ! -d "$test_dir" ]; then
    continue
  fi
  if [ ! -f "${test_dir}/Makefile" ]; then
    continue
  fi

  test_name=$(basename "$test_dir")
  run_test "$test_name" "$test_dir" ""
done

# Print summary
printf '\n%s\n' "$(printf '%0.s-' $(seq 1 40))"
printf 'Results: '
if [ "$PASS_COUNT" -gt 0 ]; then
  printf '%s%s%d passed%s' "$BOLD" "$GREEN" "$PASS_COUNT" "$RESET"
fi
if [ "$FAIL_COUNT" -gt 0 ]; then
  if [ "$PASS_COUNT" -gt 0 ]; then printf ', '; fi
  printf '%s%s%d failed%s' "$BOLD" "$RED" "$FAIL_COUNT" "$RESET"
fi
if [ "$SKIP_COUNT" -gt 0 ]; then
  if [ "$PASS_COUNT" -gt 0 ] || [ "$FAIL_COUNT" -gt 0 ]; then printf ', '; fi
  printf '%s%d skipped%s' "$YELLOW" "$SKIP_COUNT" "$RESET"
fi
printf '\n\n'

# Exit with failure if any tests failed
[ "$FAIL_COUNT" -eq 0 ]
